from Image_encoder import VitConfig
from text_encoder import TetConfig
from engram import EngramConfig
from dataclasses import dataclass
import torch.optim as optim

'''
clip(normal)
clip(+ mHC)
clip(normal + engram)
clip(mHC + engram)
--> small, base
'''

#clip config, experiment setting
@dataclass
class clip_config :
    vit_config:VitConfig
    vit_engram_config:EngramConfig

    tet_config:TetConfig
    tet_engram_config:EngramConfig

class clip_config :
    clip_s_normal = clip_config(
        vit_config = VitConfig(
                in_channels = 3,
                img_size = 224,
                patch_size = 16,
                emb_dim = 128,
                depth = 16,
                n_heads = 8,
                attn_dropout = 0.1,
                ffn_mul = 4,
                ffn_dropout = 0.1,
                use_moe = False,
                n_experts = 16,
                k = 1,
                c = 1.0,
                every_2 = False,
                use_mhc = False,
                hc_mult = 4,
                engram_cfg = None,
                device = "cuda",
        ),
        vit_engram_config = None,
        tet_config = TetConfig(
                vocab_size = 49408,
                max_ctx_len = 77,
                emb_dim = 128,
                depth = 16,
                n_heads = 8,
                attn_dropout = 0.1,
                ffn_mul = 4,
                ffn_dropout = 0.1,
                use_moe = False,
                n_experts = 16,
                k = 1,
                c = 1.0,
                every_2 = False,
                use_mhc = False,
                hc_mult = 4,
                device = "cuda",
        ),
        tet_engram_config = None,
    )

    clip_s_moe = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_s_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_s_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_s_moe_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_s_moe_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_s_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_s_moe_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 128,
                    depth = 16,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 16,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 512,
                    engram_embd_d = 1280,
                    engram_layer_n = [2, 8],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_m_normal = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_m_moe = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_m_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_m_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_m_moe_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_m_moe_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_m_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_m_moe_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 256,
                    depth = 24,
                    n_heads = 8,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 32,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 1024,
                    engram_embd_d = 2560,
                    engram_layer_n = [3, 12],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_l_normal = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_l_moe = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_l_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_l_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_l_moe_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_l_moe_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_l_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_l_moe_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 512,
                    depth = 28,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 64,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 2048,
                    engram_embd_d = 5120,
                    engram_layer_n = [4, 18],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_h_normal = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_h_moe = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_h_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_h_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_h_moe_mhc = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = None,
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = None,
    )

    clip_h_moe_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = False,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_h_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = False,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

    clip_h_moe_mhc_engram = clip_config(
            vit_config = VitConfig(
                    in_channels = 3,
                    img_size = 224,
                    patch_size = 16,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    engram_cfg = None,
                    device = "cuda",
            ),
            vit_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
            tet_config = TetConfig(
                    vocab_size = 49408,
                    max_ctx_len = 77,
                    emb_dim = 1024,
                    depth = 32,
                    n_heads = 16,
                    attn_dropout = 0.1,
                    ffn_mul = 4,
                    ffn_dropout = 0.1,
                    use_moe = True,
                    n_experts = 128,
                    k = 1,
                    c = 1.0,
                    every_2 = False,
                    use_mhc = True,
                    hc_mult = 4,
                    device = "cuda",
            ),
            tet_engram_config = EngramConfig(
                    embd_d = 4096,
                    engram_embd_d = 10240,
                    engram_layer_n = [6, 24],
                    engram_vocab_size = 226,
                    max_ngram = 3,
                ),
    )

if __name__ == "__main__" :
    from text_encoder import TET
    from Image_encoder import VIT
    import torchinfo
    import torch

    test_image = VIT(cfg=vit_model.VIT_B_32)
    vit_sum = torchinfo.summary(test_image, (10, 3, 224, 224), verbose=0, mode="train")
    estimated_total = (
        vit_sum.total_input +
        vit_sum.total_output_bytes+
        vit_sum.total_param_bytes
    )
    print(f"{round(estimated_total/1e6, 2) * 2}MB, VIT total vram usage(when using adam)")
    print(f"total {round(vit_sum.total_params/1e6, 1)}M")

    print("----------------------------------------")

    test_text = TET(cfg=tet_model.TET_B_32)
    test_data = torch.randint(0, 49407, (10, 77))
    tet_sum = torchinfo.summary(test_text, input_data=test_data, verbose=0, mode="train")
    estimated_total = (
        tet_sum.total_input +
        tet_sum.total_output_bytes+
        tet_sum.total_param_bytes
    )
    print(f"{round(estimated_total/1e6, 2) * 2}MB, TET total vram usage(when using adam)")
    print(f"total {round(tet_sum.total_params/1e6, 1)}M")
